### ISSUE TITLE
Separate WordPress project framework and the cli generator

### ISSUE THREAD

**Issue by ptt-homme** [studiometa/create-wordpress-project#87]
There are 2 advantages behind this :
- update of old project will be easier as we can only update the framework without the need of the cli
- maintain both packages will be facilitated

@studiometa/wordpress What do you think?

**Comment by titouanmathis** [comment]
What parts exactly would be separated?

**Comment by perruche** [comment]
- A repo with the project generator that contain the saofile/generator file, package.json and required deps
- A repo with the current `template` folder

The main goal of this change is to make the developping experience a little more friendly on the repository. Currently this is a painfull process, has you have to make a lot of changes to be able to use composer commands for exemple because of the generator conditions which is non-valid code.

I'm not sure this is possible to separate the 2 with sao tho.

**Comment by ptt-homme** [comment]
@studiometa/wordpress Any thoughts on that?

**Comment by titouanmathis** [comment]
Let's do it 👍

**Comment by perruche** [comment]
I think this is no longer an issue since the move to a composer project generator, right @titouanmathis  ?

**Comment by titouanmathis** [comment]
Yes, this issue will be closed by #106. We need to merge it and publish a v2 (the new structure is too different from the beta to publish it as a v1).
